all: kk part part_time

kk: kk.c
	gcc -o kk kk.c -g -lm -std=c99 -I.

part: part.c
	gcc -o part part.c random.c -g -lm -std=c99 -I.

part_time: part_time.c
	gcc -o part_time part_time.c random.c -g -lm -std=c99 -I.

